// Trig Lookup Table (Sin/Cos ROM)
// Stores sin and cos values for one full period
//
// Matches Python TrigLUT implementation
// LUT files generated by gen_trig_lut.py

module trig_lut #(
    parameter ADDR_BITS = 10,                    // 1024 entries
    parameter DATA_BITS = 25,                    // Q12.12 + sign
    parameter FRAC_BITS = 12,
    parameter SIN_FILE = "sin_lut.hex",
    parameter COS_FILE = "cos_lut.hex"
) (
    input  logic clk,
    input  logic [ADDR_BITS-1:0] angle_idx,     // Angle as table index
    output logic signed [DATA_BITS-1:0] sin_out,
    output logic signed [DATA_BITS-1:0] cos_out
);

    localparam TABLE_SIZE = 1 << ADDR_BITS;

    // ROM for sine and cosine values
    logic signed [DATA_BITS-1:0] sin_rom [0:TABLE_SIZE-1];
    logic signed [DATA_BITS-1:0] cos_rom [0:TABLE_SIZE-1];

    // Load ROM from hex files
    initial begin
        $readmemh(SIN_FILE, sin_rom);
        $readmemh(COS_FILE, cos_rom);
    end

    // Registered outputs for timing
    always_ff @(posedge clk) begin
        sin_out <= sin_rom[angle_idx];
        cos_out <= cos_rom[angle_idx];
    end

endmodule


// Dual-port version for simultaneous sin/cos lookups at different angles
module trig_lut_dual #(
    parameter ADDR_BITS = 10,
    parameter DATA_BITS = 25,
    parameter FRAC_BITS = 12,
    parameter SIN_FILE = "sin_lut.hex",
    parameter COS_FILE = "cos_lut.hex"
) (
    input  logic clk,

    // Port A - for forward sensor
    input  logic [ADDR_BITS-1:0] angle_a,
    output logic signed [DATA_BITS-1:0] sin_a,
    output logic signed [DATA_BITS-1:0] cos_a,

    // Port B - for left/right sensors
    input  logic [ADDR_BITS-1:0] angle_b,
    output logic signed [DATA_BITS-1:0] sin_b,
    output logic signed [DATA_BITS-1:0] cos_b
);

    localparam TABLE_SIZE = 1 << ADDR_BITS;

    // ROM arrays
    logic signed [DATA_BITS-1:0] sin_rom [0:TABLE_SIZE-1];
    logic signed [DATA_BITS-1:0] cos_rom [0:TABLE_SIZE-1];

    // Load ROM from hex files
    initial begin
        $readmemh(SIN_FILE, sin_rom);
        $readmemh(COS_FILE, cos_rom);
    end

    // Registered outputs
    always_ff @(posedge clk) begin
        sin_a <= sin_rom[angle_a];
        cos_a <= cos_rom[angle_a];
        sin_b <= sin_rom[angle_b];
        cos_b <= cos_rom[angle_b];
    end

endmodule
