// Auto-generated agent initialization data
// Generated by generate_cpp_agent_init.py
//
// Configuration:
//   Agents: 10
//   Resolution: 320x240
//   Spawn pattern: circle (40% radius, pointing inward)
//
// Fixed-point format: Q12.12 (12 integer bits, 12 fractional bits)
//   Scale: 4096 (1.0 = 0x1000)
//   Range: -2048.0 to +2047.9998
//

#ifndef AGENT_INIT_DATA_H
#define AGENT_INIT_DATA_H

#include <cstdint>

// Agent initialization data (circle spawn, 40% radius, pointing inward)
// Format: {x_fp, y_fp, angle_fp} for each agent
// Fixed-point: Q12.12 (scale = 4096)

const int32_t AGENT_INIT_DATA[][3] = {
    {0x00100000, 0x00078000, 0x00003244},  // Agent 0: (256.00, 120.00) px, 180.0°
    {0x000EDD00, 0x000B03A0, 0x00003C52},  // Agent 1: (237.81, 176.23) px, 216.0°
    {0x000BE1E0, 0x000D3260, 0x0000465F},  // Agent 2: (190.12, 211.15) px, 252.0°
    {0x00082720, 0x000D3560, 0x0000506D},  // Agent 3: (130.45, 211.34) px, 288.0°
    {0x000528A0, 0x000B0B80, 0x00005A7A},  // Agent 4: (82.54, 176.72) px, 324.0°
    {0x00040000, 0x00078000, 0x00000000},  // Agent 5: (64.00, 120.00) px, 0.0°
    {0x00052300, 0x0003FC60, 0x00000A0E},  // Agent 6: (82.19, 63.77) px, 36.0°
    {0x00081E20, 0x0001CDA0, 0x0000141B},  // Agent 7: (129.88, 28.85) px, 72.0°
    {0x000BD8E0, 0x0001CAA0, 0x00001E29},  // Agent 8: (189.55, 28.66) px, 108.0°
    {0x000ED760, 0x0003F480, 0x00002836}  // Agent 9: (237.46, 63.28) px, 144.0°
};

const int NUM_INIT_AGENTS = 10;

// Function to initialize agents from pre-computed data
// Usage: initialize_agents_from_precomputed(dut, num_agents);
template<typename DUT_TYPE>
void initialize_agents_from_precomputed(DUT_TYPE* dut, int num_agents) {
    for (int i = 0; i < NUM_INIT_AGENTS && i < num_agents; i++) {
        // Write x coordinate
        dut->debug_agent_idx = i;
        dut->debug_agent_sel = 0;  // 0 = x
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][0];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;

        // Write y coordinate
        dut->debug_agent_sel = 1;  // 1 = y
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][1];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;

        // Write angle
        dut->debug_agent_sel = 2;  // 2 = angle
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][2];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;
    }
    std::cout << "Initialized " << NUM_INIT_AGENTS << " agents from pre-computed data" << std::endl;
}

#endif // AGENT_INIT_DATA_H
