// Auto-generated agent initialization data
// Generated by generate_cpp_agent_init.py
//
// Configuration:
//   Agents: 100
//   Resolution: 320x240
//   Spawn pattern: circle (40% radius, pointing inward)
//
// Fixed-point format: Q12.12 (12 integer bits, 12 fractional bits)
//   Scale: 4096 (1.0 = 0x1000)
//   Range: -2048.0 to +2047.9998
//

#ifndef AGENT_INIT_DATA_H
#define AGENT_INIT_DATA_H

#include <cstdint>

// Agent initialization data (circle spawn, 40% radius, pointing inward)
// Format: {x_fp, y_fp, angle_fp} for each agent
// Fixed-point: Q12.12 (scale = 4096)

const int32_t AGENT_INIT_DATA[][3] = {
    {0x00100000, 0x00078000, 0x00003244},  // Agent 0: (256.00, 120.00) px, 180.0°
    {0x000FFD00, 0x0007DE20, 0x00003345},  // Agent 1: (255.81, 125.88) px, 183.6°
    {0x000FF460, 0x00083BE0, 0x00003447},  // Agent 2: (255.27, 131.74) px, 187.2°
    {0x000FE620, 0x00089940, 0x00003548},  // Agent 3: (254.38, 137.58) px, 190.8°
    {0x000FD1E0, 0x0008F520, 0x00003649},  // Agent 4: (253.12, 143.32) px, 194.4°
    {0x000FB560, 0x000958E0, 0x0000374B},  // Agent 5: (251.34, 149.55) px, 198.0°
    {0x000F9580, 0x0009B1C0, 0x0000384C},  // Agent 6: (249.34, 155.11) px, 201.6°
    {0x000F7060, 0x000A0860, 0x0000394E},  // Agent 7: (247.02, 160.52) px, 205.2°
    {0x000F4600, 0x000A5C60, 0x00003A4F},  // Agent 8: (244.38, 165.77) px, 208.8°
    {0x000F11E0, 0x000AB5A0, 0x00003B50},  // Agent 9: (241.12, 171.35) px, 212.4°
    {0x000EDD00, 0x000B03A0, 0x00003C52},  // ... (remaining agents)
    {0x000EA340, 0x000B4E40, 0x00003D53},
    {0x000E6560, 0x000B9580, 0x00003E54},
    {0x000E1C40, 0x000BDF00, 0x00003F56},
    {0x000DD5C0, 0x000C1D40, 0x00004057},
    {0x000D8B80, 0x000C5760, 0x00004158},
    {0x000D3DE0, 0x000C8CA0, 0x0000425A},
    {0x000CE4A0, 0x000CC180, 0x0000435B},
    {0x000C90A0, 0x000CECA0, 0x0000445C},
    {0x000C3A60, 0x000D1220, 0x0000455E},
    {0x000BE1E0, 0x000D3260, 0x0000465F},
    {0x000B7E80, 0x000D4FA0, 0x00004761},
    {0x000B2240, 0x000D6440, 0x00004862},
    {0x000AC540, 0x000D7340, 0x00004963},
    {0x000A6780, 0x000D7CA0, 0x00004A65},
    {0x000A0000, 0x000D8000, 0x00004B66},
    {0x0009A1E0, 0x000D7D00, 0x00004C67},
    {0x00094420, 0x000D7460, 0x00004D69},
    {0x0008E6C0, 0x000D6620, 0x00004E6A},
    {0x00088AE0, 0x000D51E0, 0x00004F6B},
    {0x00082720, 0x000D3560, 0x0000506D},
    {0x0007CE40, 0x000D1580, 0x0000516E},
    {0x000777A0, 0x000CF060, 0x0000526F},
    {0x000723A0, 0x000CC600, 0x00005371},
    {0x0006CA60, 0x000C91E0, 0x00005472},
    {0x00067C60, 0x000C5D00, 0x00005574},
    {0x000631C0, 0x000C2340, 0x00005675},
    {0x0005EA80, 0x000BE560, 0x00005776},
    {0x0005A100, 0x000B9C40, 0x00005878},
    {0x000562C0, 0x000B55C0, 0x00005979},
    {0x000528A0, 0x000B0B80, 0x00005A7A},
    {0x0004F360, 0x000ABDE0, 0x00005B7C},
    {0x0004BE80, 0x000A64A0, 0x00005C7D},
    {0x00049360, 0x000A10A0, 0x00005D7E},
    {0x00046DE0, 0x0009BA60, 0x00005E80},
    {0x00044DA0, 0x000961E0, 0x00005F81},
    {0x00043060, 0x0008FE80, 0x00006083},
    {0x00041BC0, 0x0008A240, 0x00006184},
    {0x00040CC0, 0x00084540, 0x00006285},
    {0x00040360, 0x0007E780, 0x00006387},
    {0x00040000, 0x00078000, 0x00000000},
    {0x00040300, 0x000721E0, 0x00000101},
    {0x00040BA0, 0x0006C420, 0x00000203},
    {0x000419E0, 0x000666C0, 0x00000304},
    {0x00042E20, 0x00060AE0, 0x00000405},
    {0x00044AA0, 0x0005A720, 0x00000507},
    {0x00046A80, 0x00054E40, 0x00000608},
    {0x00048FA0, 0x0004F7A0, 0x00000709},
    {0x0004BA00, 0x0004A3A0, 0x0000080B},
    {0x0004EE20, 0x00044A60, 0x0000090C},
    {0x00052300, 0x0003FC60, 0x00000A0E},
    {0x00055CC0, 0x0003B1C0, 0x00000B0F},
    {0x00059AA0, 0x00036A80, 0x00000C10},
    {0x0005E3C0, 0x00032100, 0x00000D12},
    {0x00062A40, 0x0002E2C0, 0x00000E13},
    {0x00067480, 0x0002A8A0, 0x00000F14},
    {0x0006C220, 0x00027360, 0x00001016},
    {0x00071B60, 0x00023E80, 0x00001117},
    {0x00076F60, 0x00021360, 0x00001218},
    {0x0007C5A0, 0x0001EDE0, 0x0000131A},
    {0x00081E20, 0x0001CDA0, 0x0000141B},
    {0x00088180, 0x0001B060, 0x0000151D},
    {0x0008DDC0, 0x00019BC0, 0x0000161E},
    {0x00093AC0, 0x00018CC0, 0x0000171F},
    {0x00099880, 0x00018360, 0x00001821},
    {0x000A0000, 0x00018000, 0x00001922},
    {0x000A5E20, 0x00018300, 0x00001A23},
    {0x000ABBE0, 0x00018BA0, 0x00001B25},
    {0x000B1940, 0x000199E0, 0x00001C26},
    {0x000B7520, 0x0001AE20, 0x00001D27},
    {0x000BD8E0, 0x0001CAA0, 0x00001E29},
    {0x000C31C0, 0x0001EA80, 0x00001F2A},
    {0x000C8860, 0x00020FA0, 0x0000202B},
    {0x000CDC60, 0x00023A00, 0x0000212D},
    {0x000D35A0, 0x00026E20, 0x0000222E},
    {0x000D83A0, 0x0002A300, 0x00002330},
    {0x000DCE40, 0x0002DCC0, 0x00002431},
    {0x000E1580, 0x00031AA0, 0x00002532},
    {0x000E5F00, 0x000363C0, 0x00002634},
    {0x000E9D40, 0x0003AA40, 0x00002735},
    {0x000ED760, 0x0003F480, 0x00002836},
    {0x000F0CA0, 0x00044220, 0x00002938},
    {0x000F4180, 0x00049B60, 0x00002A39},
    {0x000F6CA0, 0x0004EF60, 0x00002B3A},
    {0x000F9220, 0x000545A0, 0x00002C3C},
    {0x000FB260, 0x00059E20, 0x00002D3D},
    {0x000FCFA0, 0x00060180, 0x00002E3E},
    {0x000FE440, 0x00065DC0, 0x00002F40},
    {0x000FF340, 0x0006BAC0, 0x00003041},
    {0x000FFCA0, 0x00071880, 0x00003143}
};

const int NUM_INIT_AGENTS = 100;

// Function to initialize agents from pre-computed data
// Usage: initialize_agents_from_precomputed(dut, num_agents);
template<typename DUT_TYPE>
void initialize_agents_from_precomputed(DUT_TYPE* dut, int num_agents) {
    for (int i = 0; i < NUM_INIT_AGENTS && i < num_agents; i++) {
        // Write x coordinate
        dut->debug_agent_idx = i;
        dut->debug_agent_sel = 0;  // 0 = x
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][0];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;

        // Write y coordinate
        dut->debug_agent_sel = 1;  // 1 = y
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][1];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;

        // Write angle
        dut->debug_agent_sel = 2;  // 2 = angle
        dut->debug_agent_data_write = AGENT_INIT_DATA[i][2];
        dut->debug_agent_write_en = 1;
        dut->eval();
        dut->debug_agent_write_en = 0;
    }
    std::cout << "Initialized " << NUM_INIT_AGENTS << " agents from pre-computed data" << std::endl;
}

#endif // AGENT_INIT_DATA_H
